[package]
name = "mod-generator"
version = "3.0.0"
edition = "2024"

[dependencies]
clipper2-rust = "1.2"
imagequant = "4"
walkdir = "2"
kurbo = "0.11"
rayon = "1"
skrifa = "*"
read-fonts = "*"
write-fonts = "*"

[dependencies.clap]
version = "4.6"
features = ["derive"]

[dependencies.image]
version = "0.25"
default-features = false
features = ["png"]
