name: Build mod-generator

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            output-name: mod-generator.exe
            pyinstaller-args: --onefile src/main.py --name mod-generator
          - os: ubuntu-latest
            output-name: mod-generator-linux
            pyinstaller-args: --onefile src/main.py --name mod-generator-linux
          - os: macos-latest
            output-name: mod-generator-macos
            pyinstaller-args: --onefile src/main.py --name mod-generator-macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: setup uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        run: uv run pyinstaller ${{ matrix.pyinstaller-args }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output-name }}
          path: dist/${{ matrix.output-name }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: mod-generator.exe
          path: release

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: mod-generator-linux
          path: release

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: mod-generator-macos
          path: release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: true
          files: |
            release/mod-generator.exe
            release/mod-generator-linux
            release/mod-generator-macos
          name: Mod Generator ${{ github.ref_name }}
          fail_on_unmatched_files: true
